//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialExistance
    {
        public int MaterialExistanceID { get; set; }
        public int MaterialGroupID { get; set; }
        public int WareHouseID { get; set; }
        public decimal Qty { get; set; }
    
        public virtual MaterialGroup MaterialGroup { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
